#pragma once
#include <allegro5/allegro5.h>
#include <allegro5/allegro_primitives.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_ttf.h>
//#include <allegro5/allegro_image.h>
#include <Eigen/Dense>
#include <Eigen/Geometry>
#include <vector>
#include <string>
#include <fstream>
#include "parser.h"
#include <array>
#include <iostream>
#include <algorithm>
#include <utility>
#include <future>
#include <mutex>
#include <string>
#include <cmath>
#include "alEngine.h"

